# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Model-neutral text-to-video application and session implementations."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from loguru import logger

from flashdreams.demo import (
    ApplicationWarmupSessionInputs,
    CanonicalInputSchema,
    CanonicalInputWindow,
    IFlashDreamsApplication,
    IFlashDreamsApplicationSession,
    SessionInfo,
)
from flashdreams.infra.config import derive_config
from flashdreams.infra.postprocess import VideoTensorLayout
from flashdreams.infra.results import StepResult
from flashdreams.infra.time import TimeWindow
from flashdreams.runtime import StepRequirements

if TYPE_CHECKING:
    from flashdreams.runtime.demo import DemoSpec, PreparedScenario

_T2V_WARMUP_BLOCK_COUNT = 7
"""Leading AR blocks that cover observed specializations at indices 0, 1, and 6."""


@dataclass(frozen=True, kw_only=True, slots=True)
class T2VApplicationDefaults:
    """Integration-provided defaults for a text-to-video application."""

    pipeline_config: Any
    """Pipeline configuration owned by the concrete model integration."""

    total_blocks: int
    """Default number of model chunks generated by one session."""

    pixel_height: int
    """Default output frame height in pixels."""

    pixel_width: int
    """Default output frame width in pixels."""

    device: str = "cuda"
    """Default device on which the pipeline is constructed."""

    fps: float = 16.0
    """Default presentation frame rate."""

    output_layout: VideoTensorLayout = "tchw"
    """Layout emitted by the integration pipeline."""

    @classmethod
    def from_runner_config(cls, runner_config: Any) -> "T2VApplicationDefaults":
        """Derive application defaults from an integration-owned runner config."""
        required = ("pipeline", "total_blocks", "pixel_height", "pixel_width")
        missing = [name for name in required if not hasattr(runner_config, name)]
        if missing:
            raise TypeError(
                f"T2V runner config is missing application defaults: {missing}."
            )
        output_layout = getattr(
            runner_config,
            "postprocess_output_layout",
            "tchw",
        )
        if output_layout is None:
            output_layout = "tchw"
        return cls(
            pipeline_config=runner_config.pipeline,
            total_blocks=int(runner_config.total_blocks),
            pixel_height=int(runner_config.pixel_height),
            pixel_width=int(runner_config.pixel_width),
            fps=float(getattr(runner_config, "fps", 16.0)),
            output_layout=output_layout,
        )


@dataclass(frozen=True, kw_only=True, slots=True)
class _T2VSessionConfig:
    """Resolved settings for one text-to-video session."""

    pipeline_config: Any
    """Pipeline configuration selected by the concrete application."""

    prompt: str
    """Initial text prompt used to build the autoregressive cache."""

    total_blocks: int
    """Number of model chunks generated before the session completes."""

    pixel_height: int
    """Output frame height in pixels."""

    pixel_width: int
    """Output frame width in pixels."""

    device: str
    """Device on which the pipeline is constructed."""

    fps: float
    """Presentation frame rate exposed to output sinks."""

    output_layout: VideoTensorLayout
    """Layout emitted by the integration pipeline."""


class T2VApplication(IFlashDreamsApplication):
    """Reusable text-to-video application configured by one integration."""

    session_type: type["T2VApplicationSession"]

    def __init__(self, *, defaults: T2VApplicationDefaults) -> None:
        self.defaults = defaults
        self._session_config: _T2VSessionConfig | None = None
        self._pipeline: Any | None = None
        self._closed = False

    @property
    def input_schema(self) -> CanonicalInputSchema:
        """Declare that plain T2V consumes no live canonical controls."""
        return CanonicalInputSchema(description="uncontrolled text-to-video")

    @property
    def supports_session_reset(self) -> bool:
        """Return whether T2V sessions can rebuild per-generation state."""
        return True

    def init(self, commandline_args: Sequence[str]) -> None:
        """Parse session overrides and retain the required initial prompt."""
        parser = argparse.ArgumentParser(prog="flashdreams-run <t2v-slug>")
        parser.add_argument("--prompt")
        parser.add_argument(
            "--total-blocks", type=int, default=self.defaults.total_blocks
        )
        parser.add_argument(
            "--pixel-height", type=int, default=self.defaults.pixel_height
        )
        parser.add_argument(
            "--pixel-width", type=int, default=self.defaults.pixel_width
        )
        parser.add_argument("--device", default=self.defaults.device)
        parser.add_argument("--fps", type=float, default=self.defaults.fps)
        parser.add_argument(
            "--compile",
            action=argparse.BooleanOptionalAction,
            default=None,
        )
        args = parser.parse_args(list(commandline_args))

        prompt = (args.prompt or "").strip()
        if not prompt:
            raise ValueError("--prompt is required and must be non-empty.")
        if args.total_blocks <= 0:
            raise ValueError("--total-blocks must be greater than zero.")
        if args.pixel_height <= 0 or args.pixel_width <= 0:
            raise ValueError(
                "--pixel-height and --pixel-width must be greater than zero."
            )
        if args.fps <= 0:
            raise ValueError("--fps must be greater than zero.")

        pipeline_config = self.defaults.pipeline_config
        if args.compile is not None:
            pipeline_config = derive_config(
                pipeline_config,
                diffusion_model={
                    "transformer": {"compile_network": args.compile},
                },
            )
        self._session_config = _T2VSessionConfig(
            pipeline_config=pipeline_config,
            prompt=prompt,
            total_blocks=args.total_blocks,
            pixel_height=args.pixel_height,
            pixel_width=args.pixel_width,
            device=args.device,
            fps=args.fps,
            output_layout=self.defaults.output_layout,
        )

    def create_session(self) -> IFlashDreamsApplicationSession:
        """Create a model session and feed it the command-line prompt."""
        if self._session_config is None:
            raise RuntimeError(
                "T2VApplication.init() must run before create_session()."
            )
        if self._closed:
            raise RuntimeError("Cannot create a session from a closed T2V application.")
        pipeline = self._pipeline
        if pipeline is None:
            pipeline = (
                self._session_config.pipeline_config.setup()
                .to(self._session_config.device)
                .eval()
            )
            self._pipeline = pipeline
        session = self.session_type(
            config=self._session_config,
            pipeline=pipeline,
        )
        session.set_prompt(self._session_config.prompt)
        return session

    def create_model_warmup_sessions(
        self,
        spec: DemoSpec,
        scenario: PreparedScenario,
    ) -> Sequence[ApplicationWarmupSessionInputs]:
        """Warm the leading autoregressive model specializations."""
        del scenario
        if spec.output.mode != "webrtc":
            return ()
        config = self._session_config
        if config is None:
            raise RuntimeError(
                "T2VApplication.init() must run before model warmup planning."
            )
        warmup_blocks = min(config.total_blocks, _T2V_WARMUP_BLOCK_COUNT)
        return (
            ApplicationWarmupSessionInputs(
                step_inputs=tuple(
                    CanonicalInputWindow(
                        window=TimeWindow(
                            start_s=float(block_index),
                            end_s=float(block_index + 1),
                        )
                    )
                    for block_index in range(warmup_blocks)
                )
            ),
        )

    def close(self) -> None:
        """Release the application-lifetime T2V pipeline."""
        if self._closed:
            return
        self._closed = True
        pipeline = self._pipeline
        self._pipeline = None
        if pipeline is not None:
            close = getattr(pipeline, "close", None)
            if callable(close):
                close()


class T2VApplicationSession(IFlashDreamsApplicationSession):
    """Reusable cache-isolated text-to-video model session."""

    def __init__(self, *, config: _T2VSessionConfig, pipeline: Any) -> None:
        self.config = config
        self._prompt: str | None = None
        self._pipeline: Any | None = pipeline
        self._cache: Any | None = None
        self._step_index = 0
        self._closed = False

    def set_prompt(self, prompt: str) -> None:
        """Set the initial prompt before model cache initialization."""
        if self._cache is not None:
            raise RuntimeError("Cannot change the prompt after session initialization.")
        prompt = prompt.strip()
        if not prompt:
            raise ValueError("prompt must be non-empty.")
        self._prompt = prompt

    def init(self) -> None:
        """Initialize the session-local autoregressive cache."""
        if self._prompt is None:
            raise RuntimeError("Set a prompt before initializing the T2V session.")
        if self._closed:
            raise RuntimeError("Cannot initialize a closed T2V session.")
        if self._cache is not None:
            return

        pipeline = self._pipeline
        if pipeline is None:
            raise RuntimeError("T2V application pipeline is unavailable.")
        self._cache = self._initialize_cache(pipeline)

    def _initialize_cache(self, pipeline: Any) -> Any:
        decoder = getattr(pipeline, "decoder", None)
        if decoder is None or not hasattr(decoder, "spatial_compression_ratio"):
            raise TypeError(
                "T2V requires a video decoder with spatial_compression_ratio."
            )
        ratio = int(decoder.spatial_compression_ratio)
        if self.config.pixel_height % ratio or self.config.pixel_width % ratio:
            raise ValueError(
                "T2V dimensions must be divisible by the decoder spatial "
                f"compression ratio ({ratio})."
            )
        return pipeline.initialize_cache(
            text=[self._prompt],
            image=None,
            height=self.config.pixel_height // ratio,
            width=self.config.pixel_width // ratio,
        )

    def session_info(self) -> SessionInfo:
        """Return video geometry and timing for output sink initialization."""
        if self._pipeline is None:
            raise RuntimeError(
                "T2VApplicationSession.init() must run before session_info()."
            )
        frame_count = None
        get_frame_count = getattr(self._pipeline, "get_num_output_frames", None)
        if callable(get_frame_count):
            steady_index = 1 if self.config.total_blocks > 1 else 0
            frame_count = int(get_frame_count(steady_index))
        return SessionInfo(
            output_layout=self.config.output_layout,
            steady_output_frame_count=frame_count,
            frames_per_second=self.config.fps,
            video_width=self.config.pixel_width,
            video_height=self.config.pixel_height,
            metadata={"prompt": self._prompt or ""},
        )

    def next_step_requirements(self) -> StepRequirements | None:
        """Return requirements for the next video block."""
        if self._step_index >= self.config.total_blocks:
            return None
        frame_count = None
        if self._pipeline is not None:
            get_frame_count = getattr(self._pipeline, "get_num_output_frames", None)
            if callable(get_frame_count):
                frame_count = int(get_frame_count(self._step_index))
        return StepRequirements(
            step_index=self._step_index,
            input_frame_count=frame_count if frame_count is not None else 1,
            steady_output_frame_count=frame_count,
        )

    def step(self, inputs: CanonicalInputWindow) -> StepResult:
        """Generate one canonical result for the next video block."""
        if self._closed:
            raise RuntimeError("T2V session is closed.")
        if self._pipeline is None or self._cache is None:
            raise RuntimeError("T2VApplicationSession.init() must run before step().")
        if self._step_index >= self.config.total_blocks:
            raise RuntimeError("T2V session has no remaining steps.")

        if inputs.values:
            raise ValueError("T2V does not declare live canonical inputs.")
        generated = self._pipeline.generate(
            autoregressive_index=self._step_index,
            cache=self._cache,
        )
        logger.info(
            "T2V AR {} output tensor signature shape={} dtype={}",
            self._step_index,
            tuple(generated.shape),
            generated.dtype,
        )
        self._pipeline.finalize(
            autoregressive_index=self._step_index,
            cache=self._cache,
        )
        result = StepResult.from_video_chunk(
            step_index=self._step_index,
            video_chunk=generated.detach(),
            layout=self.config.output_layout,
            metadata={"prompt": self._prompt or ""},
        )
        self._step_index += 1
        return result

    def reset(self) -> None:
        """Rebuild autoregressive state on the retained T2V pipeline."""
        if self._closed:
            raise RuntimeError("Cannot reset a closed T2V session.")
        pipeline = self._pipeline
        if pipeline is None:
            raise RuntimeError("T2V application pipeline is unavailable.")
        self._cache = self._initialize_cache(pipeline)
        self._step_index = 0

    def close(self) -> None:
        """Release session-local autoregressive state."""
        if self._closed:
            return
        self._closed = True
        self._cache = None
        self._pipeline = None


T2VApplication.session_type = T2VApplicationSession


__all__ = [
    "T2VApplication",
    "T2VApplicationDefaults",
    "T2VApplicationSession",
]
